import React from 'react';

export const metadata = {
  title: 'Terms of Service | Rocket Solutions',
  description: 'Terms of Service for Rocket Solutions',
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-300 py-24">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
        
        <div className="prose prose-invert max-w-none">
          <p className="mb-6"><strong>Effective Date: April 25, 2026</strong></p>
          
          <p className="mb-6">These Terms of Service ("Terms") govern your access to and use of rocketsolutions.org and the services provided by Rocket Solutions. By accessing or using the site, you agree to be bound by these Terms.</p>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">1. Use of Services</h2>
          <p className="mb-6">You agree to use our website and AI solutions only for lawful purposes. You must not use our services to generate harmful, illegal, or discriminatory content.</p>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">2. AI Solutions Disclaimer</h2>
          <p className="mb-4">Rocket Solutions utilizes artificial intelligence and machine learning technologies. Due to the nature of AI, outputs generated by our services may not always be completely accurate, reliable, or appropriate for your specific use case.</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>You acknowledge that all AI-generated content is provided "as is."</li>
            <li>You are solely responsible for reviewing, verifying, and validating any outputs before relying on them for personal or business decisions.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">3. Intellectual Property</h2>
          <p className="mb-6">Unless otherwise stated, Rocket Solutions owns the intellectual property rights for all material on the website, excluding the user-generated inputs you provide. You grant us a license to use, host, and process your inputs to provide the services to you.</p>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">4. Limitation of Liability</h2>
          <p className="mb-6">To the fullest extent permitted by law, Rocket Solutions and its affiliates shall not be liable for any indirect, consequential, incidental, or punitive damages arising from your use of the site or any AI-generated solutions. We do not guarantee that the site will be available at all times or free from errors.</p>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">5. Governing Law</h2>
          <p className="mb-6">These Terms shall be governed by and construed in accordance with the laws of the State of Alabama, without regard to its conflict of law principles.</p>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">6. Changes to Terms</h2>
          <p className="mb-6">We reserve the right to modify these Terms at any time. We will notify users of any changes by updating the "Effective Date" of these Terms.</p>

          <h2 className="text-2xl font-semibold text-white mt-10 mb-4">7. Contact Us</h2>
          <p className="mb-2">For any questions regarding these Terms, please contact us at:</p>
          <address className="not-italic">
            <strong>Rocket Solutions</strong><br />
            <a href="mailto:business@rocketsolutions.org" className="text-blue-400 hover:text-blue-300">business@rocketsolutions.org</a>
          </address>
        </div>
      </div>
    </main>
  );
}
